version: '2'
services:
  activemq:
    image: webcenter/activemq
    environment:
    - ACTIVEMQ_ADMIN_LOGIN=admin
    - ACTIVEMQ_ADMIN_PASSWORD=admin
    - ACTIVEMQ_JMX_LOGIN=admin
    - ACTIVEMQ_JMX_PASSWORD=admin
    ports:
    - 61616:61616
    - 8161:8161

  rabbitmq:
    image: rabbitmq:latest
    environment:
    - RABBITMQ_DEFAULT_USER=admin
    - RABBITMQ_DEFAULT_PASS=admin
    ports:
    - 15672:15672
    - 5672:5672